package keymap

// catalog lists every scope and binding with its default keys. Changing a
// name or scope is a breaking config change (see AGENTS.md); changing a
// default key is not, but update the README keys table.
var catalog = []Scope{
	{Name: "main", Doc: "List and reading pane. Movement keys scroll the reader when it has focus.", Bindings: []Binding{
		{Name: "down", Keys: []string{"j"}, Desc: "down / next card target", Group: "Move"},
		{Name: "up", Keys: []string{"k"}, Desc: "up / previous card target", Group: "Move"},
		{Name: "scroll_down", Keys: []string{"down"}, Desc: "down / scroll reader", Group: "Move"},
		{Name: "scroll_up", Keys: []string{"up"}, Desc: "up / scroll reader", Group: "Move"},
		{Name: "top", Keys: []string{"g", "home"}, Desc: "top", Group: "Move"},
		{Name: "bottom", Keys: []string{"G", "end"}, Desc: "end", Group: "Move"},
		{Name: "half_page_down", Keys: []string{"ctrl+d"}, Desc: "half page down / up", Group: "Move"},
		{Name: "half_page_up", Keys: []string{"ctrl+u"}, Desc: "half page up", Pair: "half_page_down"},
		{Name: "page_down", Keys: []string{"ctrl+f", "pgdown"}, Desc: "page down / up", Group: "Move"},
		{Name: "page_up", Keys: []string{"ctrl+b", "pgup"}, Desc: "page up", Pair: "page_down"},
		{Name: "focus_views", Keys: []string{"0"}, Desc: "views panel", Group: "Move"},
		{Name: "focus_list", Keys: []string{"esc", "1"}, Desc: "list", Group: "Move"},
		{Name: "focus_reader", Keys: []string{"2"}, Desc: "reader", Group: "Move"},
		{Name: "next_pane", Keys: []string{"tab", "l"}, Desc: "next / previous pane", Hint: "pane", Group: "Move"},
		{Name: "prev_pane", Keys: []string{"shift+tab", "h"}, Desc: "previous pane", Pair: "next_pane"},
		{Name: "open", Keys: []string{"enter"}, Desc: "open ticket / edit target", Group: "Move"},
		{Name: "filter", Keys: []string{"/"}, Desc: "filter", Hint: "filter", Group: "Move"},
		{Name: "projects", Keys: []string{"p"}, Desc: "projects", Hint: "proj", Group: "Move"},
		{Name: "history", Keys: []string{"H"}, Desc: "ticket history", Group: "Move"},
		{Name: "action", Keys: []string{"space", "a"}, Desc: "run action", Hint: "act", Group: "Ticket"},
		{Name: "repeat_action", Keys: []string{"."}, Desc: "repeat last action", Group: "Ticket"},
		{Name: "pin", Keys: []string{"P"}, Desc: "pin / unpin", Group: "Ticket"},
		{Name: "edit", Keys: []string{"e"}, Desc: "edit", Hint: "edit", Group: "Ticket"},
		{Name: "comment", Keys: []string{"c"}, Desc: "add comment", Group: "Ticket"},
		{Name: "due", Keys: []string{"d"}, Desc: "set due date", Group: "Ticket"},
		{Name: "move_section", Keys: []string{"m"}, Desc: "move to section", Group: "Ticket"},
		{Name: "assign", Keys: []string{"@"}, Desc: "assign", Group: "Ticket"},
		{Name: "log_time", Keys: []string{"t"}, Desc: "log time", Hint: "time", Group: "Ticket"},
		{Name: "attachments", Keys: []string{"f"}, Desc: "attachments", Group: "Ticket"},
		{Name: "open_browser", Keys: []string{"o"}, Desc: "open in browser", Group: "Ticket"},
		{Name: "copy_link", Keys: []string{"y"}, Desc: "copy link", Hint: "copy link", Group: "Ticket"},
		{Name: "copy_comment", Keys: []string{"Y"}, Desc: "copy targeted comment", Hint: "copy comment", Group: "Ticket"},
		{Name: "reload", Keys: []string{"r"}, Desc: "reload / clear image cache", Group: "Ticket"},
		{Name: "reader_view", Keys: []string{"v"}, Desc: "cards / markdown", Group: "View"},
		{Name: "saved_views", Keys: []string{"V"}, Desc: "saved views", Group: "View"},
		{Name: "save_view", Keys: []string{"ctrl+s"}, Desc: "save current view", Group: "View"},
		{Name: "next_saved_view", Keys: []string{"]"}, Desc: "next / previous saved view", Group: "View"},
		{Name: "prev_saved_view", Keys: []string{"["}, Desc: "previous saved view", Pair: "next_saved_view"},
		{Name: "refresh_interval", Keys: []string{"R"}, Desc: "auto-update interval", Group: "View"},
		{Name: "repos", Keys: []string{"L"}, Desc: "project repos / ticket repo override", Group: "View"},
		{Name: "action_builder", Keys: []string{"A"}, Desc: "build / edit actions", Group: "View"},
		{Name: "settings", Keys: []string{"s"}, Desc: "settings", Group: "View"},
		{Name: "group_by", Keys: []string{"b"}, Desc: "group by", Group: "View"},
		{Name: "sort_by", Keys: []string{"B"}, Desc: "sort by", Group: "View"},
		{Name: "fit_list", Keys: []string{"="}, Desc: "fit list", Group: "View"},
		{Name: "help", Keys: []string{"?"}, Desc: "this help", Hint: "keys", Group: "View"},
		{Name: "quit", Keys: []string{"q"}, Desc: "quit", Group: "View"},
	}},
	{Name: "views", Doc: "Views panel (0). Other keys fall through to [keys.main].", Bindings: []Binding{
		{Name: "down", Keys: []string{"j", "down"}, Desc: "next row"},
		{Name: "up", Keys: []string{"k", "up"}, Desc: "previous row"},
		{Name: "top", Keys: []string{"g", "home"}, Desc: "first row"},
		{Name: "bottom", Keys: []string{"G", "end"}, Desc: "last row"},
		{Name: "open", Keys: []string{"enter", "l"}, Desc: "open the row"},
	}},
	{Name: "filter", Doc: "While typing a filter. Printable keys type, so these need others.", Bindings: []Binding{
		{Name: "done", Keys: []string{"enter"}, Desc: "keep the filter", Typing: true},
		{Name: "cancel", Keys: []string{"esc"}, Desc: "restore the filter from before /", Typing: true},
		{Name: "help", Keys: []string{"ctrl+/"}, Desc: "filter guide", Typing: true},
	}},
	{Name: "picker", Doc: "Pickers and menus. They start in browse mode; search opens a search field, where printable keys type.", Bindings: []Binding{
		{Name: "down", Keys: []string{"j", "down", "ctrl+n"}, Desc: "next item", Typing: true},
		{Name: "up", Keys: []string{"k", "up", "ctrl+p"}, Desc: "previous item", Typing: true},
		{Name: "top", Keys: []string{"g", "home"}, Desc: "first item"},
		{Name: "bottom", Keys: []string{"G", "end"}, Desc: "last item"},
		{Name: "choose", Keys: []string{"enter"}, Desc: "pick; in multi-select pickers, confirm the checked items", Typing: true},
		{Name: "toggle", Keys: []string{"space", "tab"}, Desc: "multi-select pickers: check or uncheck", Typing: true},
		{Name: "use_typed", Keys: []string{"ctrl+s"}, Desc: "pickers that accept typed values: use the search text", Typing: true},
		{Name: "search", Keys: []string{"/"}, Desc: "search"},
		{Name: "cancel", Keys: []string{"esc"}, Desc: "stop searching, or close", Typing: true},
	}},
	{Name: "form", Doc: "Action forms and time entry.", Bindings: []Binding{
		{Name: "next", Keys: []string{"tab", "j", "down"}, Desc: "next field"},
		{Name: "prev", Keys: []string{"shift+tab", "k", "up"}, Desc: "previous field"},
		{Name: "edit", Keys: []string{"enter"}, Desc: "edit the field"},
		{Name: "submit", Keys: []string{"ctrl+s"}, Desc: "submit"},
		{Name: "cancel", Keys: []string{"esc"}, Desc: "cancel"},
	}},
	{Name: "form_field", Doc: "While editing a form text field.", Bindings: []Binding{
		{Name: "done", Keys: []string{"enter"}, Desc: "keep the value", Typing: true},
		{Name: "next", Keys: []string{"tab"}, Desc: "keep the value and edit the next field", Typing: true},
		{Name: "cancel", Keys: []string{"esc"}, Desc: "discard the edit", Typing: true},
	}},
	{Name: "input", Doc: "Multi-line text boxes such as comments. enter adds a newline.", Bindings: []Binding{
		{Name: "submit", Keys: []string{"ctrl+s"}, Desc: "submit", Typing: true},
		{Name: "cancel", Keys: []string{"esc"}, Desc: "cancel", Typing: true},
	}},
	{Name: "builder", Doc: "Action builder (A). Its menus use [keys.picker].", Bindings: []Binding{
		{Name: "save", Keys: []string{"ctrl+s"}, Desc: "save the action"},
	}},
	{Name: "notice", Doc: "Notice popups.", Bindings: []Binding{
		{Name: "dismiss", Keys: []string{"enter", "esc"}, Desc: "dismiss"},
	}},
}
